#
# Makefile for sensor chip drivers.
#
ccflags-$(CONFIG_THERMAL_DEBUG) := -DDEBUG
obj-$(CONFIG_OMAP4_DIE_TEMP_SENSOR)	+= omap_temp_sensor.o
obj-$(CONFIG_OMAP4_PCB_SENSOR)	+= pcb_temp_sensor.o
obj-$(CONFIG_OMAP4_TMP102_SENSOR)	+= tmp102_temp_sensor.o
obj-$(CONFIG_OMAP4_JET_TMP102)	+= jet_temp_sensor.o
